### ISSUE TITLE
emails and buying orders

### ISSUE THREAD

**Issue by djdavidi** [djdavidi/ninetiesStore#93]
+1. populate the email template with the real data about the order
2. clicking 'Purchase' button should fail (validation popup) if  user didn't enter Email & Shipping Address

**Comment by thinkocapo** [comment]
11/08/15 sending emails works. I stored the API Key in a file behind the ninetiesstore directory, so the key doesnt get uploaded to GitHub. Follow the path and make this file&key yourself if you want to test it on your machine. I'll send you emails for now. I will included it when rdy to push to Heroku.

And I'm working on the above ^^ issues in Description
